#$ -S /bin/sh

#$ -pe smp 24
#$ -cwd
#$ -V


#$ -N scRNAseq_analysis_OPC

#$ -e ../Logs/scRNAseq_analysis_OPC.err
#$ -o ../Logs/scRNAseq_analysis_OPC.out

#$ -r y

ncores=24

projdir=/home/finotello/myScratch/Projects/scRNA-seq/vanderBurg_Oropharyngeal_Cancer/
indir=$projdir"Fastq/"

outdir_gex=$projdir"/GEX/"
outdir_tcr=projdir"/TCR/"

files_gex=OPC_GEX_files.txt
ls $indir | grep "_GEX" > $files_gex

files_gex=OPC_TCR_files.txt
ls $indir | grep "_TCR" > $files_tcr

while read cfile
do

	sample=`basename $cfile | sed 's/_GEX$//g'`
	id=`echo $sample | sed 's/^.*_//g'`
	fastqs=$indir$sample
	fastqs_gex=$fastqs"_GEX/"
	fastqs_tcr=$fastqs"_TCR/"

	if [ "$id" != "160" ]
	then 
		continue
	fi

	echo $id

	# GEX analysis
	#bash scRNAseq_analysis_GEX.sh -i $id -f $fastqs_gex -s $sample -n $ncores -o $outdir_gex -c auto
	#SC5P-R2

	# TCR analysis
	bash scRNAseq_analysis_TCR.sh -i $id -f $fastqs_tcr -s $sample -n $ncores -o $outdir_tcr

done < $files_gex
