#$ -S /bin/sh

#$ -pe smp 24
#$ -cwd
#$ -V


#$ -N scRNAseq_analysis_OPC_TCR

#$ -e ../Logs/scRNAseq_analysis_OPC_TCR.err
#$ -o ../Logs/scRNAseq_analysis_OPC_TCR.out

#$ -r y

ncores=24

projdir=/home/finotello/myScratch/Projects/scRNA-seq/vanderBurg_Oropharyngeal_Cancer/
indir=$projdir"Fastq/"

outdir_tcr=projdir"/TCR/"

files_tcr=OPC_TCR_files.txt
ls $indir | grep "_TCR" > $files_tcr

while read cfile
do

	sample=`basename $cfile | sed 's/_TCR$//g'`
	id=`echo $sample | sed 's/^.*_//g'`
	fastqs=$indir$sample
	fastqs_tcr=$fastqs"_TCR/"

	echo $id

	# TCR analysis
	bash scRNAseq_analysis_TCR.sh -i $id -f $fastqs_tcr -s $sample -n $ncores -o $outdir_tcr

done < $files_tcr
